spring.application.name=HospitalPortal

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_portal
spring.datasource.username=root
spring.datasource.password=tiendat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true